# Generated by Django 5.1.5 on 2025-03-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='match',
            table='match_users',
        ),
        migrations.AlterModelTable(
            name='tournament',
            table='tournament_users',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_users',
        ),
    ]
