# Generated by Django 5.1.5 on 2025-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars'),
        ),
    ]
