# Generated by Django 5.1.5 on 2025-02-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tournament_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournament_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.tournament'),
        ),
    ]
