# Generated by Django 5.1.5 on 2025-03-13 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_match_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players_alias',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_set', to='api.tournament'),
        ),
    ]
