# Generated by Django 5.1.5 on 2025-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_42_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
