# Generated by Django 5.1.5 on 2025-03-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tournament_players_alias_tournament_round_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='round',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='rounds_json',
            new_name='matches_json',
        ),
    ]
