# Generated by Django 5.1.5 on 2025-03-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_round_tournament_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='match',
            new_name='game',
        ),
    ]
