# Generated by Django 5.1.5 on 2025-02-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tournament_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player1_id',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='player2_id',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='winner_id',
            new_name='winner',
        ),
    ]
