# Generated by Django 5.1.5 on 2025-03-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_match_tournament_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='game',
            new_name='match',
        ),
    ]
