# Generated by Django 5.1.5 on 2025-02-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_player1_id_match_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intra_user',
            field=models.BooleanField(default=False),
        ),
    ]
