# Generated by Django 5.1.5 on 2025-03-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_game_tournament_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
    ]
