# Generated by Django 5.1.5 on 2025-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_intra_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_42_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
